# Generated by Django 5.2.1 on 2026-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userbook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
